### ISSUE TITLE
Artefacts not available

### ISSUE THREAD

**Issue by jmvandebron** [sbt/sbt-dynver#239]
Hi, we're having trouble adding your plugin to our sbt builds, because the artefacts cannot be found.

Can you tell us if/when the latest version will be published on Sonatype (https://www.scala-sbt.org/1.x/docs/Using-Sonatype.html)?

**Comment by xuwei-k** [comment]
👍 

- https://github.com/sbt/sbt/issues/7202 🤔

**Comment by SethTisue** [comment]
Some volunteer assistance that would be extremely helpful here would be for someone to send a PR that moves the publishing onto sbt-ci-release, so that new releases can easily be published to Maven Central. If that was in place, somebody (maybe Eugene or Dale or myself) could take care of adding the needed secrets to GitHub Actions, so we (perhaps one of us, or, better, a volunteer maintainer) could easily roll a 4.1.2.

**Comment by SethTisue** [comment]
Note that once sbt/sbt#7202 is resolved, the plugin will again be available from repo.scala-sbt.org, as it always has been.

**Comment by turb** [comment]
If you're mainly stuck because CI has to download it, and if it works locally because of your local cache, a temporary workaround is including the JAR file in your project:
```
mkdir project/lib
cp ~/.ivy2/cache/scala_2.12/sbt_1.0/com.dwijnand/sbt-dynver/jars/sbt-dynver-4.1.1.jar project/lib
```

Then remove/comment out `addSbtPlugin("com.dwijnand" % "sbt-dynver" % "4.1.1")` from `project/plugins.sbt` and commit/push.

This JAR is 65KB, which is sustainable to be included in git.

(I have no experience in pushing to Maven Central, so it's better I don't mess with it)

**Comment by SethTisue** [comment]
@turb very helpful — I just opened sbt/sbt#7206 as a place to collect such information. could you say this there?

**Comment by mkurz** [comment]
@SethTisue I can add the cli-release plugin, shouldn't be too hard and you can add the secrets meanwhile. Doing that I would also migrate to the `com.github.sbt` groupid (and also let scala steward know about that).

However, the last stable release is [4.1.1](https://github.com/sbt/sbt-dynver/releases/tag/v4.1.1) and it looks like current master is for version 5 already, since there exists a [5.0.0-M3](https://github.com/sbt/sbt-dynver/releases/tag/v5.0.0-M3) release. So if we want to publish v4 on maven central, I don't really know where to branch of a `4.x` branch.
So I would just add ci-release onto current master for now, however the v5.0.0-M3 release was cut over 2 years ago already, so is someone actually working on this plugin here? Or does anyone know when it is ready for a final v5 release? Like what is missing?

**Comment by mkurz** [comment]
Here we go: #242

**Comment by eed3si9n** [comment]
Unlike most other plugins, @dwijnand is still active, so I think Dale should have say on if he'd rather manually publish to Maven Central using his organization name.

**Comment by dwijnand** [comment]
I'm happy to move it to the shared org name.

**Comment by mkurz** [comment]
There is https://github.com/scala-steward-org/scala-steward/pull/3026 already :wink:

**Comment by mzuehlke** [comment]
scala-steward migration is merged
